-- create schema assesment2

-- use assesment2

CREATE TABLE PATIENT (
PATIENTID CHAR (4),
PATIENTNAME VARCHAR(30),
PATIENTDOB DATE,
PATIENTADDRESS VARCHAR(30),
PRIMARY KEY (PATIENTID)
);

CREATE TABLE DOCTOR(
DOCTORID CHAR(4),
DOCTORNAME VARCHAR(30),
DOCTORADDRESS VARCHAR(30),
DOCTORDESIGNATION VARCHAR(20),
DOCTORSALARY INTEGER,
PRIMARY KEY (DOCTORID)
);

CREATE TABLE APPOINTMENT (
APPOINTMENTID CHAR (4),
APPOINTMENTDATE DATE,
APPOINTMENTTIME TIME,
PATIENTID CHAR(4),
DOCTORID CHAR(4),
PRIMARY KEY (APPOINTMENTID),
FOREIGN KEY (PATIENTID) REFERENCES PATIENT (PATIENTID),
FOREIGN KEY (DOCTORID) REFERENCES DOCTOR (DOCTORID)
);

CREATE TABLE INVOICE (
INVOICENUMBER CHAR (4),
INVOICEDATE DATE,
INVOICEAMOUNT NUMERIC(4,2),
APPOINTMENTID CHAR(4),
PRIMARY KEY (INVOICENUMBER),
FOREIGN KEY (APPOINTMENTID) REFERENCES APPOINTMENT (APPOINTMENTID)
);



CREATE TABLE PAYMENT(
PAYMENTID CHAR(4),
PAYMENTAMOUNT NUMERIC(4,2),
PAYMENTDATE DATE,
INVOICENUMBER CHAR(4),
PRIMARY KEY (PAYMENTID),
FOREIGN KEY (INVOICENUMBER) REFERENCES INVOICE (INVOICENUMBER));


ALTER TABLE PATIENT DROP COLUMN PATIENTADDRESS;

ALTER TABLE PATIENT ADD COLUMN PATIENTSUBURB VARCHAR(30);

INSERT INTO PATIENT (PATIENTID,PATIENTNAME,PATIENTDOB,PATIENTSUBURB) VALUES('P001','ANDREW STRAUSS','1960-09-25','CHATSWOOD');
INSERT INTO PATIENT (PATIENTID,PATIENTNAME,PATIENTDOB,PATIENTSUBURB) VALUES('P002','MICHAEL HOLDING','1950-08-20','RYDE');
INSERT INTO PATIENT (PATIENTID,PATIENTNAME,PATIENTDOB,PATIENTSUBURB) VALUES('P003','BRIAN LARA','1966-10-15','BURWOOD');
INSERT INTO PATIENT (PATIENTID,PATIENTNAME,PATIENTDOB,PATIENTSUBURB) VALUES('P004','COURTNY WASH','1960-09-25','HOLLYWOOD');
INSERT INTO PATIENT (PATIENTID,PATIENTNAME,PATIENTDOB,PATIENTSUBURB) VALUES('P005','ALAN DONALD','1970-05-05','RODES');
INSERT INTO PATIENT (PATIENTID,PATIENTNAME,PATIENTDOB,PATIENTSUBURB) VALUES('P006','ABDUL QADIR','1980-07-10','AUBURN');

INSERT INTO DOCTOR VALUES ("D001","SHANE WARNE","MARSFILED","GP", 150000);
INSERT INTO DOCTOR VALUES ("D002","BRETT LEE","RYDE","SURGEON", 160000);
INSERT INTO DOCTOR VALUES ("D003","WAQAR YOUNAS","MACQUARIE PARK","SURGEON",200000);	
INSERT INTO DOCTOR VALUES ("D004","CHAMINDA VAS","BURWOOD","GASTROLOGIST", 100000);
INSERT INTO DOCTOR VALUES ("D005","SAQLAIN MUSHTAQ","NEW CASTLE","GP", 150000);	
INSERT INTO DOCTOR VALUES ("D006","JAMES ANDERSON","LONDON","PHYSICIAN", 120000);


INSERT INTO APPOINTMENT VALUES ("AP01","2023-01-01","13:30:00","P001","D001");
INSERT INTO APPOINTMENT VALUES ("AP02","2023-01-11","14:30:00","P002","D002");
INSERT INTO APPOINTMENT VALUES ("AP03","2023-01-20","10:00:00","P003","D003");
INSERT INTO APPOINTMENT VALUES ("AP04","2020-04-25","11:00:00","P004","D004");
INSERT INTO APPOINTMENT VALUES ("AP05","2020-05-18","12:00:00","P005","D001");
INSERT INTO APPOINTMENT VALUES ("AP06","2022-08-06","15:30:00","P006","D002");
INSERT INTO APPOINTMENT VALUES ("AP07","2021-09-09","09:30:00","P002","D005");
INSERT INTO APPOINTMENT VALUES ("AP08","2022-02-15","10:00:00","P002","D006");
INSERT INTO APPOINTMENT VALUES ("AP09","2019-10-01","13:15:00","P003","D001");
INSERT INTO APPOINTMENT VALUES ("AP10","2019-12-02","16:00:00","P004","D005");


INSERT INTO INVOICE VALUES ("I001","2023-01-01","50.50","AP01");
INSERT INTO INVOICE VALUES ("I002","2023-01-11","90.00","AP02");	
INSERT INTO INVOICE VALUES ("I003","2023-01-20","80.00","AP03");	
INSERT INTO INVOICE VALUES ("I004","2020-04-25","70.00","AP04");	
INSERT INTO INVOICE VALUES ("I005","2020-05-18","80.50","AP05");	
INSERT INTO INVOICE VALUES ("I006","2022-08-06","85.00","AP06");	
INSERT INTO INVOICE VALUES ("I007","2021-09-09","90.00","AP07");	
INSERT INTO INVOICE VALUES ("I008","2022-02-15","50.00","AP08");	
INSERT INTO INVOICE VALUES ("I009","2019-10-01","40.00","AP09");
INSERT INTO INVOICE VALUES ("I010","2019-12-02","60.00","AP10");



INSERT INTO PAYMENT (PAYMENTID,PAYMENTAMOUNT,PAYMENTDATE,INVOICENUMBER) VALUES ('P001',50.50,'2023-01-10','I001');
INSERT INTO PAYMENT (PAYMENTID,PAYMENTAMOUNT,PAYMENTDATE,INVOICENUMBER) VALUES ('P002',90.00,'2023-01-11','I002');
INSERT INTO PAYMENT (PAYMENTID,PAYMENTAMOUNT,PAYMENTDATE,INVOICENUMBER) VALUES ('P003',80.00,'2023-01-20','I003');
INSERT INTO PAYMENT (PAYMENTID,PAYMENTAMOUNT,PAYMENTDATE,INVOICENUMBER) VALUES ('P004',70.00,'2021-04-25','I004');
INSERT INTO PAYMENT (PAYMENTID,PAYMENTAMOUNT,PAYMENTDATE,INVOICENUMBER) VALUES ('P005',80.50,'2021-05-18','I005');
INSERT INTO PAYMENT (PAYMENTID,PAYMENTAMOUNT,PAYMENTDATE,INVOICENUMBER) VALUES ('P006',50.00,'2022-09-06','I006');
INSERT INTO PAYMENT (PAYMENTID,PAYMENTAMOUNT,PAYMENTDATE,INVOICENUMBER) VALUES ('P007',50.00,'2021-09-09','I007');
INSERT INTO PAYMENT (PAYMENTID,PAYMENTAMOUNT,PAYMENTDATE,INVOICENUMBER) VALUES ('P008',50.00,'2023-02-15','I008');
INSERT INTO PAYMENT (PAYMENTID,PAYMENTAMOUNT,PAYMENTDATE,INVOICENUMBER) VALUES ('P009',40.50,'2019-10-02','I009');

SELECT * FROM PATIENT;
SELECT * FROM DOCTOR;
SELECT * FROM APPOINTMENT;
SELECT * FROM INVOICE;
SELECT * FROM PAYMENT;

-- task 1 

select patientname, CONCAT(
      SUBSTR(patientname, 1, 1),".", 
      SUBSTR(patientname, INSTR(patientname, ' ') + 1, 1)) AS Initials 
from patient where patientdob<'2000-01-01';


-- task 2 

select * from doctor 
where (doctordesignation in('PHYSICIAN') or doctoraddress like 'M%') 
AND doctorsalary>150000;

-- task 3 
-- I USE THE FUNCTION MONTH TO EXTRACT month of a date , i knew that concept , and i took a look in 
-- https://www.w3schools.com/sql/func_mysql_month.asp
select appointment.*,invoice.invoiceamount 
from appointment 
join invoice using(appointmentid) 
where MONTH(appointmentdate)=5 or invoice.invoiceamount>85;

-- task 4
-- in this query i use subquerys with this result  i use like table and set the alias for this table 'mydata' 
-- and extract date from table  patient and filter using the patientdob equals dateval extracted from table 'mydata'

SELECT patientname,textage FROM ( select max(patientdob) as dateval ,'youngest' as textage from patient
union select min(patientdob) as dateval,'Oldest' as textage from patient) AS mydata,patient 
where patient.patientdob=mydata.dateval;


-- task 5 
-- I use the doctorid o could be posible with doctorname='Shane Warne'
select patientname from patient where PATIENTID IN(select PATIENTID from appointment join doctor using(doctorid) where doctorid='D001');

-- task 6
select invoicenumber,invoicedate,coalesce(invoice.invoiceamount-payment.paymentamount,invoice.invoiceamount) as remaining_amount 
from  invoice  left join payment using(invoicenumber) WHERE 
COALESCE(invoice.invoiceamount - payment.paymentamount, invoice.invoiceamount) > 0;


-- task 7 

select doctorname,count(appointment.appointmentid) as totalappo 
from doctor join appointment using (doctorid)
where doctorname like '%e'
group by doctorname
having totalappo>1;


-- task 8 
CREATE VIEW APPOINTMENT_DETAILS AS
SELECT patient.patientname,doctor.doctorname,appointment.appointmentdate,appointment.appointmenttime
FROM patient
join appointment using(patientid)
join doctor using (doctorid)
order by  appointment.appointmentdate asc


-- select * from APPOINTMENT_DETAILS

-- task 9 
DELIMITER //
CREATE PROCEDURE INVOICE_DETAILS (inputpatient varchar(30))
BEGIN
	select invoice.invoicenumber,invoice.invoicedate,invoice.invoiceamount 
    from invoice join appointment using (appointmentid) 
    join patient using(patientid)
    where patient.patientname=inputpatient;
END//

-- SELECT * FROM PATIENT
CALL INVOICE_DETAILS('ABDUL QADIR')





